name: PR Triggered Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  verify-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"
